baseURL = 'https://saguaropodcast.com/'
defaultContentLanguage = 'en'
# Emoji in markdown files
enableEmoji = true
languageCode = 'en-us'
# Number of blog post per page
paginate = 10
theme = 'pico'
# Title of the website is used for the meta tag title
# and the square icon (not the favicon)
title = 'Saguaro Podcast'

[params]
customCSS = [
	"style/style.css",
	"style/theme.sass",
] # Path relative to assets folder
# customJS = ["js/console.js"] # Path relative to assets folder
# Homepage description
description = "Saguaro Podcast"
email = "rcamacho96@gmail.com"
favicon = '/saguaro-icon-192.png'
darkMode = true

# Social parameters for contact_icons widget
# [[params.social]]
# alt = "email icon"
# icon = "/icons/email.svg"
# name = "email"
# url = "mailto:mail@example.com"

# [[params.social]]
# alt = "twitter icon"
# blank = true
# icon = "/icons/twitter.svg"
# name = "twitter"
# url = "https://twitter.com/"

# Navigation bar
[menu]

[[menu.main]]
identifier = "home" # identifier is use for translations
pre = "" # pre is inserted before the translation (icons, image, etc)
url = "/" 
weight = 10 

[[menu.main]]
identifier = "episodes" # identifier is use for translations
pre = "" # pre is inserted before the translation (icons, image, etc)
url = "/episodes/" 
weight = 20 

# [[menu.main]]
# identifier = "contact" # identifier is use for translations
# pre = "" # pre is inserted before the translation (icons, image, etc)
# url = "/#contact" 
# weight = 30 

# Syntax highlightning
# [markup.highlight]
# guessSyntax = true 
# lineNumbersInTable = true 
# noClasses = false # Set to false to use the Pico default theme.
# tabWidth = 2 

[taxonomies]
category = "categories"
tag = "tags"

# Translation
# English, French and Italian are supported but you can contribute
# by adding translation to i18n/ folder.
[languages.en]
contentDir = 'content/en'
languageCode = 'en'
languageName = 'English'
weight = 0

# Uncomment the following lines to add an spanish translation.
# [languages.es]
# contentDir = 'content/es'
# languageCode = 'es'
# languageName = 'Español'
# weight = 4
